#Author: V Nani Kalyan
#Date: 20-Nov-2019
#Description: yml file to build the Mobile API Services

version: 0.2
          
phases:
  install:
    runtime-versions:                
        nodejs: 12.19.1
        #nodejs: 12.15.0
    commands: 
      - npm install pm2@latest -g
      - npm install --production
  pre_build:
    commands:      
  build:
    commands:
      - pm2 start sprintProcesses.yml
  post_build:
    commands:
      - echo Build completed on `date`
      - sleep 5
      - pm2 ls
      - sleep 5
      - pm2 stop all      
      - pm2 delete all
artifacts:
  files:
    - '**/*'
  discard-paths: no
