apps:
  - name : "Main"
    env: {mode: prod}
    script   : ./main.js
    instances: max    
    out_file: '/dev/null'
    exec_mode: cluster
    
  - name : "ConsumerZero"
    env: {mode: prod, partition: 0}
    script   : ./consumer.js
    out_file: '/dev/null'
    instances: 1
    exec_mode: fork
  
  - name : "Widget_ConsumerZero"
    env: {mode: prod, partition: 0}
    script   : ./consumerServices/widgetEngine/server.js
    out_file: '/dev/null'
    instances: 1
    exec_mode: fork

  - name : "Log_ConsumerZero"
    env: {mode: prod, partition: 0}
    script   : ./logConsumer.js
    out_file: '/dev/null'
    instances: 1
    exec_mode: fork
    
  #- name : "Log_ConsumerOne"
  #  env: {mode: prod, partition: 1}
  #  script   : ./logConsumer.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
    
  #- name : "Log_ConsumerTwo"
  #  env: {mode: prod, partition: 2}
  #  script   : ./logConsumer.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
    
  #- name : "Widget_ConsumerOne"
  #  env: {mode: prod, partition: 1}
  #  script   : ./consumerServices/widgetEngine/server.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
    
  #- name : "Widget_ConsumerTwo"
  #  env: {mode: prod, partition: 2}
  #  script   : ./consumerServices/widgetEngine/server.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
    
  #- name : "Widget_ConsumerThree"
  #  env: {mode: prod, partition: 3}
  #  script   : ./consumerServices/widgetEngine/server.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
    
  #- name : "Widget_ConsumerFour"
  #  env: {mode: prod, partition: 4}
  #  script   : ./consumerServices/widgetEngine/server.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
    
  #- name : "Widget_ConsumerFive"
  #  env: {mode: prod, partition: 5}
  #  script   : ./consumerServices/widgetEngine/server.js
  #  out_file: '/dev/null'
  #  instances: 1
  #  exec_mode: fork
  