/**
 * author: SBK
 */

module.exports = {
    WIDGET_TYPE_IDS: {
        SINGLE_DIMENSIONAL_AGGR: 1,
        MULTI_DIMENSIONAL_AGGR: 2,
        FREQUENCY_DISTRIBUTION: 3,
        MULTI_VALUE_VISUALIZATION: 4,
        FORM_FILE_STATUS_DISTRIBUTION: 5,
        FORM_FILE_STATUS_DURATION: 6,
        FORM_FILE_STATUS_TRANSITION: 7,
        FORM_FILE_DISTRIBUTION: 8,
        SINGLE_DIMENSIONAL_STATUS_AGGR: 11
    }
}