version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      # - REPOSITORY_URI=012345678910.dkr.ecr.us-east-1.amazonaws.com/base-image
      - echo "REPOSITORY_URI is $REPOSITORY_URI"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "COMMIT_HASH is $COMMIT_HASH"
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "IMAGE_TAG is $IMAGE_TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f docker/staging.api.Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"staging-api-service","imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"staging-api-service","imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imageDetail.json # This was basically a mistake, it should have been just imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json # This was basically a mistake, it should have been just imagedefinitions.json